# ~/.config/hypr/hyprlock.conf

background {
    path = $HOME/.assets/wallhaven-q2155r.jpg
    blur_size = 5
    blur_passes = 1
    contrast = 1.0
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.6
}

general {
    hide_cursor = false
}
input-field {
    monitor = 
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    fade_on_empty = false
    placeholder_text = Continue Adventure...
    
    inner_color = rgba(1915267F)     
    font_color = rgb(7E59BF)
    fail_color = rgb(FF0000)
    outer_color = rgb(8D3031)
    capslock_color = rgb(FFCD56)

    position = 0, -120
    halign = center
    valign = center
}
auth {
	pam:enabled = true
	pam:module = hyprlock
	fingerprint:enabled = true
	fingerprint:ready_message = (󰈷) 
}
label {	
    text = $FPRINTPROMPT  $FPRINTFAIL
    font_family = JetBrainsMono Nerd Font
    font_size = 16
    position = 0, -180
    halign = center
    valign = center
    color = rgba(200, 200, 200, 1.0)
}

label {
    text = $TIME
    font_family = JetBrainsMono Nerd Font
    font_size = 50
    position = 0, 0
    halign = center
    valign = center
    color = rgba(E66B26CC)
}

