wallpaper {
	monitor = eDP-1
	path = /home/vetula/.assets/wallhaven-3kwll9.jpg
	fit_mode = cover
}
wallpaper {
	monitor = DP-2
	path = /home/vetula/.assets/halo_prototype_hud___blue_by_entereri_d2ux0xc-pre.jpg
	fit_mode = cover
}
splash = false
