layerrule {
	name= wofi-rules
	match:namespace = wofi
	animation = slide bottom linear
}
layerrule {
	name=layer-slide-top
	match:namespace = ^(waybar|swaync-notification-window|swaync-control-center)$
	animation = slide top
	no_screen_share = off
}
layerrule {
	name=layer-slide-right
	match:namespace = ^(swaync-control-center)$
	animation = slide right
	no_screen_share = off
}
layerrule {
	name=layer-slide-bottom
	match:namespace = ^(swayosd)$
	animation = slide bottom
	no_screen_share = off
}
