windowrule {
	name = debug
	match:class = ^(wofi)$
	decorate = off
	rounding = 0
}
windowrule {
	name = no-bar
	match:float = false
	hyprbars:no_bar = on
}

windowrule {
	name = no_looking
	match:class = ^(.*(obs).*)$
	no_screen_share = on
}
windowrule {
	name = smart-border
	match:workspace = w[tv1]
	match:float = 0
	decorate = off
	rounding = 0
	border_size = 0
}
windowrule {
	name = Kitty
	match:class = ^(kitty)$
	hyprbars:no_bar = on
}
windowrule {
	name = emoji
	match:title = ^(HyprEmoji)$
	hyprbars:no_bar = on
}
windowrule {
	name = Steam-Rules
	match:class = ^(steam)$
	match:title = ^(.+)$
	float = on
	animation = gnomed
	border_color = rgba(171D25)
	size = monitor_w*0.6 monitor_h*0.8
	center = on
	rounding = 0
	decorate = off
	hyprbars:no_bar = on
}
windowrule {
	name = Steam-Menu-Rules
	match:class = ^(steam)$
	match:title = ^$
	float = on
	no_focus = on
	hyprbars:no_bar = on
}
windowrule {
	name = communication
	match:class = ^(discord|org.telegram.desktop|elecwhat)$
	size = monitor_w*0.6 monitor_h*0.6
	center = on
	float = on
	rounding = 1
}
windowrule {
	name = thunar
	match:class = ^(thunar)$
	size = monitor_w*0.5 monitor_h*0.5
	center = on
	float = on
	rounding = 2
	border_size= 1
}
windowrule {
	name = PIP-Rules
	match:title = ^(.*Picture-in-Picture.*|.*Bild-im-Bild.*)$
	border_color = rgb(ff0000)
	float = on
	move = 0 0 
	size = 450 250
	rounding = 0
	pin = on
	hyprbars:no_bar = on
}
windowrule {
	name = WiFi
	match:class = ^(wifi)$
	float = on
	size = monitor_w*0.5 monitor_h*0.5
	move = monitor_w*0.5 50 
	animation = slide right
	hyprbars:no_bar = on
}
windowrule {
	name= Task-Manager
	match:class = ^(btop)$
	float = on
	size = 730 710
	animation = slide top
	center = on
	hyprbars:no_bar = on
}
windowrule {
	name = Pavucontroll
	match:class =^(org.pulseaudio.pavucontrol|update)$
	size = monitor_w*0.4 monitor_h*0.4
	move = monitor_w*0.6 50
	float = on
	animation = slide right
	rounding = 0
	hyprbars:no_bar = on
}
windowrule {
	name = Clock
	match:class=^(clock)$
	float = on
	move = monitor_w*0.4 50px
	size = monitor_w*0.2 monitor_h*0.1
	no_blur=on
	border_color = rgba(00000000)
	animation = slide top
}
windowrule {
	name = YouTube
	match:title = ^(.*YouTube.*)$
	border_color = rgb(ffdd0000)
}
windowrule {
	name=Steam-Big-Picture
	match:title = ^(Steam Big Picture Mode)$
	border_size = 0
	dim_around = on
	tile = on
	hyprbars:no_bar = on
}
windowrule {
	name=Steam_Apps
	match:class = ^(steam_app.*)$
	float = on
	stay_focused = on
	rounding = 0
	hyprbars:no_bar = on
}
windowrule {
	name=Ignore-Maximize
	match:class = .*
	suppress_event = maximize
}
windowrule {
	name = xwayland-fix
	match:class = ^$
	match:title = ^$
	match:xwayland = 1
	match:float = 1
	match:fullscreen = 0
	match:pin = 0
	no_focus = on
}
windowrule {
	name = nvim
	match:title = ^(.*nvim.*)$
	rounding = 0
	hyprbars:no_bar = on
	no_screen_share = on
	opaque = on
	idle_inhibit = focus
	decorate = on
	border_color = rgba(fe7446ff)
	border_size = 4
}
